# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1497wd6jXsVaLOt-Hk6vgorXGWeasDUDt
"""

from datetime import date

d1=int(input("enter  day created"))
m1=int(input("enter  month created"))
y1=int(input("enter  year created"))

print(" enter expiry date details")


d2=int(input("enter  day deleted"))
m2=int(input("enter  month deleted"))
y2=int(input("enter  year deleted"))


def server_cost(y1,y2,m1,m2,d1,d2):
  start_date = date(y2, m2, d2)
  end_date = date(y1, m1, d1)
  d = start_date - end_date
  d=int(d.days) 
  if d<0:
    print("The date server deleted is less than date created")
  if d>=365:
    p=2000
    return p
  elif d>30 and d<=365:
    p=d*1000
    return p
  elif d>1 and d<=30:
    p=d*30
    return p
  else:
    p=20
    return p

price=server_cost(y1,y2,m1,m2,d1,d2)   
print(price)