# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q47MBqXwb8WLlj6x7zdoinQDqbeuXB9i
"""

list=[30,20,10]
length=len(list)

for i in list:
  print(i)
  if i%30==0:
    c=c+1
print("Number of adds in slot",c)